[project]
name = "urbanize"
version = "0.1.0"
description = "Aplicativo de gestão para corretores imobiliários"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.116.1",
]
